# Generated by Django 3.1.8 on 2023-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='apply_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
